parallel-jobs = 1

[1-1-1-1]
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet/"
# package-name = com.cloudflare.onedotonedotonedotone
patches-source = "rushiranpise/morphe-patches"
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
rv-brand = "Morphe"
build-mode = "apk"
version = "auto"
# uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"

[Adguard]
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard"
# package-name = com.adguard
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
rv-brand = "Morphe"
build-mode = "apk"
version = "auto"
patches-source = "hoo-dles/morphe-patches"
# uptodown-dlurl = "https://adguard-for-android.en.uptodown.com/android"

[Automate]
apkmirror-dlurl = "https://www.apkmirror.com/apk/llamalab/automate-llamalab"
# package-name = com.llamalab.automate
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
rv-brand = "Morphe"
build-mode = "apk"
version = "auto"
patches-source = "BholeyKaBhakt/android-patches-xtra"
# uptodown-dlurl = "https://automate-beta.en.uptodown.com/android"

[CamScanner]
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator"
# package-name = com.intsig.camscanner
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "hoo-dles/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android"

[casetracker]
# package-name = com.saldous.casetracker
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
rv-brand = "Morphe"
patches-source = "rushiranpise/morphe-patches"
apkpure-dlurl = "https://apkpure.com/case-tracker-for-uscis/com.saldous.casetracker"
apkcombo-dlurl = "https://apkcombo.com/case-tracker-us-immigration/com.saldous.casetracker/"
# uptodown-dlurl = "https://case-tracker-for-uscis.en.uptodown.com/android"

[citizen]
# package-name = sp0n.citizen
apkmirror-dlurl = "https://www.apkmirror.com/apk/sp0n-inc/citizen-safety-awareness/"
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "rushiranpise/morphe-patches"
rv-brand = "Morphe"
apkpure-dlurl = "https://apkpure.com/citizen-protect-the-world/sp0n.citizen"
# uptodown-dlurl = "https://citizen.en.uptodown.com/android"

[crimeradar]
# package-name = com.newsbreak.crimeradar
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "rushiranpise/morphe-patches"
rv-brand = "Morphe"
apkpure-dlurl = "https://apkpure.com/crimeradar-dispatch-alerts/com.newsbreak.crimeradar"
apkcombo-dlurl = "https://apkcombo.com/crimeradar-dispatch-alerts/com.newsbreak.crimeradar/"
# uptodown-dlurl = "https://crimeradar.en.uptodown.com/android"

[Cube-ACR]
apkmirror-dlurl = "https://www.apkmirror.com/apk/cube-systems/call-recorder-cube-acr/"
# package-name = com.catalinagroup.callrecorder
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "rushiranpise/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://cube-acr.en.uptodown.com/android"

[DocScanner]
apkmirror-dlurl = "https://www.apkmirror.com/apk/lufick/document-scanner-pdf-creator"
# package-name = com.cv.docscanner
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
rv-brand = "Morphe"
# uptodown-dlurl = "https://doc-scanner.en.uptodown.com/android"

[Duolingo]
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
# package-name = com.duolingo
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "hoo-dles/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://duolingo.en.uptodown.com/android"

[Eyecon]
apkmirror-dlurl = "https://www.apkmirror.com/apk/eyecon-phone-dialer-contacts/eyecon-caller-id-spam-block"
# package-name = com.eyecon.global
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
rv-brand = "Morphe"
# uptodown-dlurl = "https://eyecon-phone-dialer-and-cont-eyecon.en.uptodown.com/android"

[Facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
github-dlurl = "hhttps://github.com/nvbangg/builder-for-morphe/releases/tag/com.facebook.katana"
# package-name = com.facebook.katana
archive-dlurl = "https://archive.org/download/geologically/apks/com.facebook.katana/"
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "meridianfresco/morphe-meta-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://facebook.en.uptodown.com/android"

[Fing]
apkmirror-dlurl = "https://www.apkmirror.com/apk/fing-limited/fing-network-tools"
# package-name = com.overlook.android.fing
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
rv-brand = "Morphe"
# uptodown-dlurl = "https://fing-network-tools.en.uptodown.com/android"

[Google-Photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
# package-name = com.google.android.apps.photos
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
included-patches = """\
    'Enable DCIM folders backup control' \
    """
patches-source = "RookieEnough/De-Vanced"
rv-brand = "Morphe"
# uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Instagram]
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
# package-name = com.instagram.android
archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android/"
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "crimera/piko"
rv-brand = "Morphe"
# uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[Komoot]
apkmirror-dlurl = "https://www.apkmirror.com/apk/komoot-gmbh/komoot-cycling-hiking-mountain-biking-maps"
# package-name = de.komoot.android
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "brosssh/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://komoot.en.uptodown.com/android"

[MacroDroid]
apkmirror-dlurl = "https://www.apkmirror.com/apk/arlosoft/macrodroid-device-automation-2"
# package-name = com.arlosoft.macrodroid
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
rv-brand = "Morphe"
# uptodown-dlurl = "https://macrodroid.en.uptodown.com/android"

[Mapy]
apkmirror-dlurl = "https://www.apkmirror.com/apk/seznam-cz-a-s/mapy-cz-navigation-off-maps"
# package-name = cz.seznam.mapy
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "brosssh/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://mapy-cz.en.uptodown.com/android"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# package-name = com.google.android.apps.youtube.music
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Proton-Mail]
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
# package-name = ch.protonmail.android
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "Morphe"
# uptodown-dlurl = "https://protonmail.en.uptodown.com/android"

[Proton-Vpn-Paresh]
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
# package-name = ch.protonvpn.android
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
rv-brand = "Morphe"
# uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
# package-name = com.reddit.frontpage
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Speedtest]
apkmirror-dlurl = "https://www.apkmirror.com/apk/ookla/speedtest"
# package-name = org.zwanoo.android.speedtest
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "BholeyKaBhakt/android-patches-xtra"
rv-brand = "Morphe"
# uptodown-dlurl = "https://speedtest-net-mobile.en.uptodown.com/android"

[Splitwise]
apkmirror-dlurl = "https://www.apkmirror.com/apk/splitwise/splitwise"
# package-name = com.Splitwise.SplitwiseMobile
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "rushiranpise/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://splitwise.en.uptodown.com/android"

[Strava]
# package-name = com.strava
apkpure-dl = "https://apkpure.com/strava-run-hike-android-exercise-laugh/com.strava"
apkcombo-dl = "https://apkcombo.com/strava/com.strava/"
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "Morphe"
# uptodown-dlurl = "https://strava.en.uptodown.com/android"

[Telegram]
# package-name = org.telegram.messenger.web
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
rv-brand = "Morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram-web-version/"
apkcombo-dlurl = "https://apkcombo.com/telegram/org.telegram.messenger.web/"
apkpure-dlurl = "https://apkpure.com/telegram-messenger/org.telegram.messenger.web"
# uptodown-dlurl = "https://telegram.en.uptodown.com/android"

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
# package-name = com.zhiliaoapp.musically
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "Morphe"
# uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[Transit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/transit-app-inc/transit-real-time-transit-app"
# package-name = com.thetransitapp.droid
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
excluded-patches = """\
  'Custom Maps API Key' \
  """
patches-source = "andronedev/morphe-patches"
rv-brand = "Morphe"
apkpure-dl = "https://apkpure.com/transit-subway-bus-times/com.thetransitapp.droid"
# uptodown-dlurl = "https://transit.en.uptodown.com/android"

[Truecaller]
# package-name = com.truecaller
archive-dlurl = "https://archive.org/download/geologically/apks/com.truecaller/"
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
rv-brand = "Morphe"

[Twitter]
# package-name = com.twitter.android
version = "11.81.0-release.0"
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android/"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/x-twitter"
patches-source = "crimera/piko"
rv-brand = "Morphe"
# uptodown-dlurl = "https://twitter.en.uptodown.com/android/"

[Unimote]
apkpure-dlurl = "https://apkpure.com/universal-tv-remote-control/sensustech.universal.tv.remote.control"
# package-name = sensustech.universal.tv.remote.control
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "rushiranpise/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://unimote.en.uptodown.com/android"

[WPS-Office]
# package-name = cn.wps.moffice_eng
archive-dlurl = "https://archive.org/download/geologically/apks/cn.wps.moffice_eng/"
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "hoo-dles/morphe-patches"
rv-brand = "Morphe"

[Xodo]
apkmirror-dlurl = "https://www.apkmirror.com/apk/apryse-software-inc/xodo-pdf-reader-editor"
# package-name = com.xodo.pdf.reader
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "hoo-dles/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://xodo-docs.en.uptodown.com/android"

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# package-name = com.google.android.youtube
arch = "arm64-v8a"
dpi = "nodpi anydpi"
enabled = true
build-mode = "apk"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
rv-brand = "Morphe"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
